project:
  type: website

website:
  title: "Andrew Belz- Data Science Portfolio"
  back-to-top-navigation: true
  repo-url: "https://github.com/pbelz1"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: resume.html
        text: My Resume
      - href: projects.html
        text: Projects

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



